
version: 0.2

phases:
  install:
    commands:
      - set -e
      - echo "cfn-guard install"
      - curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
      - cfn-guard validate -d cf-templates/simple-cf.yml -r cfn-guard-templates/ec2-checks.rules

